export const QATAR_VEHICLE_CATALOG: Record<string, string[]> = {
  Toyota: [
    "Yaris",
    "Corolla",
    "Camry",
    "Avalon",
    "Prius",
    "C-HR",
    "RAV4",
    "Fortuner",
    "Land Cruiser Prado",
    "Land Cruiser",
    "Hilux",
    "Hiace",
    "Coaster",
    "Raize",
    "Urban Cruiser",
    "Crown",
  ],
  Lexus: ["IS", "ES", "LS", "RC", "LC", "UX", "NX", "RX", "GX", "LX", "LM"],
  Nissan: [
    "Sunny",
    "Sentra",
    "Altima",
    "Maxima",
    "Versa",
    "Kicks",
    "X-Trail",
    "Qashqai",
    "Pathfinder",
    "Patrol",
    "Patrol Safari",
    "Armada",
    "Navara",
    "Z",
    "GT-R",
  ],
  Infiniti: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  Honda: ["City", "Civic", "Accord", "HR-V", "CR-V", "ZR-V", "Pilot", "Odyssey"],
  Acura: ["TLX", "RDX", "MDX"],
  Mitsubishi: ["Attrage", "Lancer", "ASX", "Eclipse Cross", "Outlander", "Montero Sport", "Pajero", "L200"],
  Suzuki: ["Dzire", "Ciaz", "Baleno", "Swift", "Vitara", "Jimny", "Ertiga", "XL7"],
  Isuzu: ["D-Max", "MU-X", "N-Series"],

  Hyundai: [
    "Accent",
    "Elantra",
    "Sonata",
    "Azera",
    "i10",
    "i20",
    "i30",
    "Kona",
    "Tucson",
    "Santa Fe",
    "Palisade",
    "Creta",
    "Staria",
  ],
  Kia: [
    "Pegas",
    "Rio",
    "Cerato",
    "K5",
    "K8",
    "Picanto",
    "Seltos",
    "Sportage",
    "Sorento",
    "Telluride",
    "Carnival",
    "Sonet",
  ],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],

  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-9", "CX-90", "MX-5"],
  Subaru: ["Impreza", "Legacy", "WRX", "Crosstrek", "Forester", "Outback", "Ascent", "BRZ"],

  Ford: ["Figo", "Focus", "Taurus", "Mustang", "Escape", "Edge", "Explorer", "Expedition", "Ranger", "F-150"],
  Lincoln: ["Corsair", "Nautilus", "Aviator", "Navigator"],
  Chevrolet: ["Spark", "Aveo", "Malibu", "Camaro", "Trailblazer", "Traverse", "Tahoe", "Suburban", "Captiva", "Silverado"],
  GMC: ["Terrain", "Acadia", "Yukon", "Sierra", "Canyon"],
  Cadillac: ["CT4", "CT5", "XT4", "XT5", "XT6", "Escalade"],
  Buick: ["Enclave", "Encore GX"],

  Jeep: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator"],
  Dodge: ["Charger", "Challenger", "Durango"],
  Ram: ["1500", "2500", "3500"],
  Chrysler: ["300", "Pacifica"],

  "Mercedes-Benz": [
    "A-Class",
    "C-Class",
    "E-Class",
    "S-Class",
    "CLA",
    "CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "G-Class",
    "V-Class",
    "AMG GT",
    "EQE",
    "EQS",
  ],
  BMW: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6", "X7", "XM", "i4", "i5", "i7", "iX"],
  Mini: ["Cooper", "Cooper S", "Countryman", "Clubman"],
  Audi: ["A3", "A4", "A6", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron", "RS6", "RS Q8"],
  Volkswagen: ["Polo", "Golf", "Jetta", "Passat", "T-Roc", "Tiguan", "Touareg", "Teramont"],
  Porsche: ["718 Cayman", "718 Boxster", "911", "Panamera", "Macan", "Cayenne", "Taycan"],
  Opel: ["Corsa", "Astra", "Crossland", "Mokka", "Grandland"],

  Peugeot: ["208", "2008", "301", "3008", "5008", "508", "Partner"],
  Renault: ["Symbol", "Megane", "Koleos", "Duster", "Arkana", "Captur", "Master"],
  Citroen: ["C3", "C4", "C5 Aircross", "Berlingo"],

  Fiat: ["500", "500X", "Tipo", "Doblo"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale"],
  Ferrari: ["Roma", "Portofino M", "296 GTB", "SF90 Stradale", "Purosangue"],
  Lamborghini: ["Huracan", "Revuelto", "Urus"],
  Maserati: ["Ghibli", "Quattroporte", "Levante", "Grecale", "MC20"],

  "Land Rover": ["Defender", "Discovery Sport", "Discovery", "Range Rover Evoque", "Range Rover Velar", "Range Rover Sport", "Range Rover"],
  Jaguar: ["XE", "XF", "F-PACE", "E-PACE", "I-PACE", "F-TYPE"],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga"],
  "Rolls-Royce": ["Ghost", "Phantom", "Cullinan", "Spectre"],
  "Aston Martin": ["Vantage", "DB11", "DB12", "DBX"],
  McLaren: ["GT", "Artura", "750S"],

  Volvo: ["S60", "S90", "XC40", "XC60", "XC90", "C40"],
  Polestar: ["Polestar 2", "Polestar 3", "Polestar 4"],

  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],

  BYD: ["Atto 3", "Dolphin", "Seal", "Han", "Tang", "Song Plus", "Qin Plus"],
  MG: ["MG5", "MG6", "MG7", "ZS", "HS", "RX5", "RX8", "One", "Marvel R"],
  Geely: ["Emgrand", "Preface", "Coolray", "Azkarra", "Monjaro", "Okavango", "Geometry C"],
  Changan: ["Alsvin", "Eado", "UNI-V", "CS35 Plus", "CS55 Plus", "CS75 Plus", "UNI-K", "UNI-T"],
  GAC: ["Empow", "GS3", "GS4", "GS8", "EMKOO", "M8"],
  Chery: ["Arrizo 5", "Arrizo 8", "Tiggo 2 Pro", "Tiggo 4 Pro", "Tiggo 7 Pro", "Tiggo 8 Pro"],
  Exeed: ["LX", "TXL", "VX", "RX"],
  Jetour: ["X70", "X70 Plus", "X90 Plus", "Dashing", "T2"],
  Haval: ["Jolion", "H6", "H6 GT", "Dargo", "H9"],
  "Great Wall": ["Poer", "Wingle 7"],
  Tank: ["Tank 300", "Tank 500"],
  BAIC: ["X35", "X55", "BJ40", "BJ60"],
  JAC: ["J7", "JS4", "JS6", "T8", "Sunray"],
  Maxus: ["D60", "D90", "T60", "V80"],
  "Dongfeng": ["AX7", "Shine", "Rich 6"],
};

export const QATAR_MANUFACTURERS = Object.keys(QATAR_VEHICLE_CATALOG);

export function getModelsByManufacturer(manufacturer: string): string[] {
  return QATAR_VEHICLE_CATALOG[manufacturer] ?? [];
}
